Add devtoolset-8-{perftools,toolchain} sources
sclorg/devtoolset-container pull request #40
Opened 2019-05-27 07:52 UTC by pkubatrh

2019-05-27 08:57 UTC, pkubatrh commented
[test]

2019-05-27 10:54 UTC, pkubatrh commented
[test]

2019-05-27 11:42 UTC, pkubatrh commented
@mpolacek Hi Marek, can you check why the tests are failing for devtoolset-8-perftools? I suspect its something to do with how the `test_sanity_ocount_run` changed between versions.

In devtoolset-7-perftools the test is skipped when a specific message is found in the output:
https://github.com/sclorg/devtoolset-container/blob/master/7-perftools/test/run#L102

but for devtoolset-8-perftools this happens only when the architecture is s380x:
https://github.com/pkubatrh/devtoolset-container/blob/add_devtoolset8/8-perftools/test/run#L124

Is this correct? Or should there be two if clauses, one for each skip?

2019-06-19 10:15 UTC, hhorak commented
I think this specific check might be influenced not only by different architectures, but also by different settings of the kernel, and I can imagine this check might never work correctly in our CI tests. I've checked that this upstream test is different from what we have downstream even for devtoolset-7 and since we don't pull code from github to downstream for these devtoolset images, my opinion is that we can have the difference for devtoolset-8 as well.

2019-06-19 10:16 UTC, hhorak commented
[test]

2019-07-10 07:38 UTC, pkubatrh commented
I did not notice that the tests are different even for 7-perftools, so makes sense I guess to include the same changes even for 8-perftools.

Done so in the latest commit, lets see if tests pass now

2019-07-10 07:47 UTC, pkubatrh commented
[test]

2019-07-18 07:31 UTC, pkubatrh commented
[test]

2020-01-23 08:44 UTC, pkubatrh commented
[test]

2020-01-23 09:58 UTC, phracek requested changes
Some changes which need to be fixed. But thanks for the update devtoolset-container.

2020-01-23 09:58 UTC, phracek commented on 8-perftools/Dockerfile
> +    yum -y clean all --enablerepo='*'
```suggestion
    yum clean all -y
```

2020-01-23 09:58 UTC, phracek commented on 8-perftools/Dockerfile.rhel7
> +    yum -y clean all --enablerepo='*'
```suggestion
    yum clean all -y
```

2020-01-23 09:58 UTC, phracek commented on 8-perftools/cccp.yml
> +job-id: devtoolset-7-perftools-centos7
devtoolset-7 is intended? Shouldn't be there `devtoolset-8`?

2020-01-23 09:58 UTC, phracek commented on 8-toolchain/Dockerfile
> +    yum -y clean all --enablerepo='*'
```suggestion
    yum clean all -y
```

2020-01-23 09:58 UTC, phracek commented on 8-toolchain/Dockerfile.fedora
> +FROM registry.fedoraproject.org/f27/s2i-core:latest
Just a question. Do we really want to support this a bit older image?
What about at least f29? Or even f31 where is a fixed issue https://github.com/sclorg/s2i-base-container/pull/198 although it is not related to C/C++.

2020-01-23 09:58 UTC, phracek commented on 8-toolchain/Dockerfile.rhel7
> +    yum -y clean all --enablerepo='*'
```suggestion
    yum clean all -y
```

2020-01-23 10:43 UTC, phracek requested changes
Please rebase PR.
I  would be glad if you can update also `README.md` file in the top directory.

2020-01-23 10:43 UTC, phracek commented on 8-toolchain/cccp.yml
> +job-id: devtoolset-7-toolchain-centos7
```suggestion
job-id: devtoolset-8-toolchain-centos7
```

2020-03-04 09:22 UTC, closed without merging

2020-03-04 12:39 UTC, pkubatrh commented
We will no longer be maintaining the image sources upstream for devtoolset-8 and newer images. We are still open for PRs though.